### ISSUE TITLE
Complete user onboarding

### ISSUE THREAD

**Issue by WillieCubed** [UTDNebula/jupiter#10]
# Overview

As a student user, I should be able to go through an onboarding process that asks me information to get set up with the service.

# Proposal

- [ ] Allow for sign-up during onboarding
- [ ] Ask a user for their interests during onboarding
- [ ] Provide a user recommendations for clubs and events during onboarding
- [ ] Show a confirmation dialog

## Supplementary Information

Please see the mock-ups [here](https://www.figma.com/file/snmEoRUgfjAZYSc6hqySkY/Wireframes-for-Jupiter?node-id=21%3A138)

**Comment by Jake3231** [comment]
Linked `10-onboarding` branch. Please change if code for this change is elsewhere.
