### ISSUE TITLE
Update README with new deployment info

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#101]
### What did you expect to happen?

I expect the README to include correct links to current deployments.

### What happened?

The Readme file has outdated/nonfunctioning links to deployments.

### Version

Pre-release (Development)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
@dlaunikitis Would you recommend keeping the Vercel badge on our Readme? It is currently not working, though I'm not sure that it's even needed.

**Comment by dlaunikitis** [comment]
@Jake3231 I don't see the necessity of keeping it around, so I don't see any issue with removing it
