### ISSUE TITLE
Enable the search bar in the Directory

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#104]
# Overview

As a user, I should be able to search for orgs using a search field in the Directory page. This is a critical feature for a basic use case.

Likely, the search functionality should consider the title of each org, and potentially the description. For performance reasons, we should consider what data we want to search.

For this issue, typing into the search field should reduce the number of results shown in the Directory. The search could happen after the user presses the enter key, or after the user has stopped typing for x seconds (likely both should be supported). Autocomplete is not needed at this stage. Additionally, animating the results changing would be nice to have but is not critical for this initial implementation.
# Proposal

- [ ] Implement basic backend support
- [ ] Enable filtering displayed orgs
- [ ] Filter based upon text entered into search bar

**Comment by Buchimi** [comment]
Proposal:
For an easy solution to this problem. We could look for a function that checks to see if a club and or it's description contains their users input string. 
```
//invalid code
str.hasString(user_input)
```

Preferred solution:
Firebase has queries. We could use the query tool to query for users
I'll dig into this. I have an implementation but it hasn't been tested
