### ISSUE TITLE
Auth UI needed

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#109]
# Overview

As a user, I should be able to sign in to Jupiter using one of a few standard login methods.

Currently, there is no auth UI, though we should create a UI that interfaces with Firebase to allow users to log in with either a username and password, or a Google account.

# Proposal
This likely depends on #99 

For this Issue, only a placeholder UI is needed that can be later wired up to the actual auth code.

- [ ] Create new Auth sheet or page
- [ ] Allow it to be shown/dismissed using sign in button in navbar

**Comment by Jake3231** [comment]
Onboarding is covered by @shreyon312 's UI in #10

**Comment by RubenOlano** [comment]
This was closed by #134
