### ISSUE TITLE
Click box for organizations are too big

### ISSUE THREAD

**Issue by Buchimi** [UTDNebula/jupiter#11]
If you hover around the org cards in the directory page, you will notice that their click box is way larger than their apparent size.

**Comment by Jake3231** [comment]
Possibly fixed in https://github.com/UTDNebula/jupiter/pull/13

**Comment by Buchimi** [comment]
The spacing behaviour is correct now but when i checked out the pull request the click box was still too big
![unknown](https://user-images.githubusercontent.com/61808599/166091812-42207d0b-9f6c-4a12-acb6-2700ad67aaf4.png)

**Comment by Jake3231** [comment]
Please see the updated code in that PR.

**Comment by Jake3231** [comment]
@Buchimi is this issue still occurring with the latest changes to `develop`?

**Comment by RubenOlano** [comment]
I think we're good to close this issue

**Comment by Jake3231** [comment]
Looks like this is no longer occurring on the latest Preview branch. Please reopen the issue if this is still happening.
