### ISSUE TITLE
Improved functionality for filter UI

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#110]
# Overview

As a user, I should be able to filter orgs in the Directory based upon a few key pieces of information, such as category.

Currently, there is placeholder UI on the left side of the directory listings, though we should finalize the things we want to filter by, and collapsible UI for each one.

# Proposal

- [ ] Decide the most important things that should be used for filtering
- [ ] Implement each category as a collapsible section in the left sidebar
- [ ] If needed, build new UI for the type of data it's filtering by (checkboxes/text field/radio buttons/etc)

**Comment by Jake3231** [comment]
This likely will need to be refocused to include new filtering UI for the new redesign. Currently orgs are listed on the homepage, and we don't have any advanced filtering methods. I'd suggest collaborating with Solomon as well.

**Comment by RubenOlano** [comment]
We probably need to add an enum to clubs so that they can be filtered into the new categories

**Comment by RubenOlano** [comment]
For now, I'm going to close this issue and make a new one once we have some more product research on how we want to do this
