### ISSUE TITLE
Update sample org data

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#111]
### What did you expect to happen?

I expect to have sample org data better matching what real orgs might use.

### What happened?

Current sample data is mostly placeholder data

### Version

Pre-release (Development)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
To add on Firebase

**Comment by Jake3231** [comment]
See latest deployments

**Comment by RubenOlano** [comment]
How many samples should we shoot for?

**Comment by RubenOlano** [comment]
We have some sample data now. Need to hook up real data in the future
