### ISSUE TITLE
More dynamic contact buttons

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#112]
# Overview

As a user, I should be able to see more visually interesting contact buttons in org detail page.

Contact buttons could have a custom color for some contact methods, and should support actually linking to data.

# Proposal

- [ ] Support linking to contact method
- [ ] Support a few custom background overrides

**Comment by Jake3231** [comment]
This will likely be scrapped, or will need to be reworked for the new design

**Comment by RubenOlano** [comment]
This still needs to be implemented in the new design. Consult [Figma](https://www.figma.com/file/snmEoRUgfjAZYSc6hqySkY/Wireframes-for-Jupiter?type=design&node-id=1356-3146&mode=design&t=UXRf3LhShub0gxUJ-0) for more info

**Comment by RubenOlano** [comment]
Yup, for now try implementing a rough draft of this and we can implement some more design once we have something working

**Comment by RubenOlano** [comment]
Closed by #136
