### ISSUE TITLE
Navigation: Hamburger menu may appear alongside regular nav buttons

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#12]
# Overview

Currently, the hamburger menu may appear in the nav bar when a regular desktop window is resized to a lower width.
![Screen Shot 2022-04-29 at 11 21 11 AM](https://user-images.githubusercontent.com/13911970/165984644-5ad2ecb1-6326-4f21-9898-de9effa32249.png)

# Expected Behavior

When reducing the width of the browser window, the nav bar should either hide the nav buttons and replace them with the mobile-style hamburger button, or rather it should continue to show the regular nav items, but not both.

**Comment by Buchimi** [comment]
it looks like adding ```hidden md:block``` 
to the class here 
![image](https://user-images.githubusercontent.com/61808599/168709226-0f609588-fd85-4a45-ace7-8fc3b5315e72.png)
fixes things
