### ISSUE TITLE
Design Refinement

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#125]
# Overview
This task is tracking v2 design refinements

After the initial implementation, there are a few low-hanging fruit changes to spruce up our UI/UX.

# Proposal

- Make sidebar liked and like button on club cards consistent (either heart or thumb up)
- Update logo design (need to consult Hilary)
- Remove `Active` label from club info page
- Add template contact buttons in club info page
- Ensure club search bar remains in club detail page
- Disable or hide Liked and History tabs
- Hide scroll bar on tags on homepage

Can add more here

**Comment by Jake3231** [comment]
Opening a new branch to begin investigating some changes

**Comment by RubenOlano** [comment]
I was able to hide the scrollbar in the #121 branch. I had to create a CSS class to do this
