### ISSUE TITLE
Migrate code to Next.js 13

### ISSUE THREAD

**Issue by Master7130** [UTDNebula/jupiter#128]
# Overview

Upgrade current code base to make use of features from Next.js 13.

# Proposal

Rename the `pages` directory to `app` and nest the pages we currently have inside their own folders inside the app directory as specified by Next.js 13.

The import for the `<Image />` component will need to be modified so that it uses Next.js 12's image component until we confirm upgrading the components to the newer version won't break existing code.

The `_app.tsx` file will need to be replaced by the `layout.tsx` file.

The `<Head />` component will need to be replaced by Next.js 13 built in SEO.

**Comment by Master7130** [comment]
@Jake3231 @RubenOlano What are your thoughts on upgrading to Next.js 13?

**Comment by RubenOlano** [comment]
I'm honestly not 100% against it. We'd just have to accommodate the code base to use the app directory. I think currently the only obstacle is that trpc doesn't support the app directory rn

**Comment by RubenOlano** [comment]
Actually, I think the trpc branch has nextjs 13, just not the app directory changes

**Comment by Master7130** [comment]
[Setup tRPC Server and Client in Next.js 13 App Directory](https://codevoweb.com/setup-trpc-server-and-client-in-nextjs-13-app-directory/)

Found this article. Should I check and see whether this actually works?

**Comment by RubenOlano** [comment]
Feel free to check it out. Let me know if its feasible to implement or not

**Comment by Jake3231** [comment]
Is this resolved by #121 ?

**Comment by Master7130** [comment]
Doesn't look like it is. I'll create a branch and test migrating now that the trpc pull request is merged.

**Comment by Master7130** [comment]
I tried getting trpc to work with nextjs 13 app directory but there were multiple issues with it. I doubt we'll be able to use the app directory without a rewrite of the trpc code but someone else should check and confirm. 

Until then we can still upgrade to nextjs 13 and continue to use the pages directory.

**Comment by RubenOlano** [comment]
I think currently we have updated to Next13 with pages dir. We can keep an eye out for trpc updates that would allow us to move to app dir
