### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#130]
# Overview

As a user, I should be able to use a login page in order to authenticate.

For now, we don't have a dedicated platform to sign in so this will be based on the current [planner](https://planner.utdnebula.com/auth/login) sign-in flow

<img width="840" alt="image" src="https://github.com/UTDNebula/jupiter/assets/76502130/52b32ae0-6516-4c6c-9ea6-6ae2a6c3159b">
For the time being, try to keep it limited to using Google as the provider

Make sure you understand how next-auth works with redirects in order to properly implement the flow and make a seamless experience for the user.

**Comment by Master7130** [comment]
Can I work on this?

**Comment by RubenOlano** [comment]
I can assign it to you for now but I believe Daniel is working on implementing NextAuth at the moment. So for now try implementing the style and look and once Daniel's done you can try integrating it to the flow
