### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#131]
# Overview

As a  user, I should be able to see the Nebula Logo on the Jupiter sidebar

The current implementation of the logo just has the word Jupiter rather than any other Nebula branding
Ideally, we would have the Nebula Logo alongside the project name to keep consistency among projects
<img width="181" alt="image" src="https://github.com/UTDNebula/jupiter/assets/76502130/8d145244-478d-4b9a-81b2-dba685d54a02">
<img width="225" alt="image" src="https://github.com/UTDNebula/jupiter/assets/76502130/c5ee094d-1740-48f7-8245-6f423f91d492">
This [Figma](https://www.figma.com/file/nC9ebFJgigw2Po2SXQHt6K/Nebula-Labs-Logo?type=design&mode=design&t=QrDHNyrPt23blbXW-1) file should include different sizes of the logo in case the ones already in the project don't quite fit

Feel free to reach out to me or the design team if you have any questions on Figma or need further clarification

**Comment by MistahSanta** [comment]
Hello, can I get assign to this issue? I am not on the team, but I believe I can handle this issue.

**Comment by RubenOlano** [comment]
For now this issue is going to be blocked until the interest form request forms have been completed
