### ISSUE TITLE
Padding Issues

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#132]
# Overview

As a user, I should be able to see the correct design for the Jupiter project

Currently, the implemented design only really follows the design at a distance. A lot of the margins and padding are not ideal and require some tweaking

Look at the [Jupiter Figma](https://www.figma.com/file/snmEoRUgfjAZYSc6hqySkY/Wireframes-for-Jupiter?type=design&node-id=1329%3A1637&mode=design&t=BmEIiTjucdjdHbb8-1) (under pages that have `redesign`) to look at how padding and margins should properly be implemented

Use the dev feature for Figma as it makes it easier to implement

**Comment by nl32** [comment]
I'd like to work on this. should I just fix the padding or all the styling to be more like the figma?

**Comment by RubenOlano** [comment]
Try fixing all the styling to reflect the figma more closely
