### ISSUE TITLE
Search bar disappears

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#137]
### What did you expect to happen?

I expected to be able to search for orgs within an org info page

### What happened?

Currently the search bar disappears whenever navigating to the info page 

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KennethImphean** [comment]
Could I work on this even though I wasn't matched to the project?

**Comment by RubenOlano** [comment]
Go for it, just make a separate branch and make a pull request once you're ready for code review
