### ISSUE TITLE
User Information

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#141]
# Overview

As a user, I should be able to edit information about myself through a settings page

Right now, we don't have an updated design for the settings page, but this can be a rough draft for now. Currently, the user metadata contains the user's name, major, minor (optional), year, career, and clubs they are a part of. A settings page should allow users to edit this information about them through some form that they can submit to view changes. 

For this issue, you will need to look into how to use drizzle in order to make tables and relationships between tables. You will also need to connect the user metadata to a `userId` within next-auth.

**Comment by RubenOlano** [comment]
[NextAuth](https://next-auth.js.org/configuration/callbacks#session-callback) stuff can also help with this. The callback can help you set data within the session object

**Comment by danielsuhcompsci** [comment]
I can work on this. Is it fine if I have the userId (from users table) as a primary key for the userMetadata table?

**Comment by RubenOlano** [comment]
Yea, that works best since we can access their id directly from the session object
