### ISSUE TITLE
Feature: Create minimally-functional homepage

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#15]
# Overview

As a student, I should be able to view a homepage showing a navigation bar, search bar, and top events. The first step is to implement a non-functional page that adheres to the design spec.

The homepage is the landing page of Jupiter and is critical in ensuring that users get a good impression of the app. The current design spec lays a good foundation for how this should look:

![](https://user-images.githubusercontent.com/13911970/164367586-3e52bded-fe67-4668-8339-fc3ec3e2cb07.png)

# Proposal

The existing homepage contains some elements of the required design, though misses many elements such as a search bar, events, and correct scrolling behavior.

According to the design, the header should collapse into a compact search bar while scrolling through events listed on the homepage.

# Tasks

- [x] https://github.com/UTDNebula/jupiter/issues/9
- [x] https://github.com/UTDNebula/jupiter/issues/5

**Comment by RubenOlano** [comment]
How does this goal change with the new redesign?
