### ISSUE TITLE
"Events" tab links to nothing

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#16]
### What did you expect to happen?

I expect that when clicking the "Events" tab in the navigation bar the top right of the screen that the app will display a non-404 page.

### What happened?

When clicking the "Events" button, a "404 not found" error is shown. The Events page needs to be initialized, and linked to the Events nav button.

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by Jake3231** [comment]
Awesome, I'll move this issue to you. Please review the message in Discord regarding procedure to make changes.
