### ISSUE TITLE
Remove Member Count From Orgs

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#162]
# Overview

Nothing too big, we've moved away from the member count on each card as we don't have a plan on how to gather a member count

**Comment by Ninad-S** [comment]
I will work on it

**Comment by RubenOlano** [comment]
Do we have any updates on this?

**Comment by Ninad-S** [comment]
Yes, I have completed the changes. I created a branch locally, but do not have the permission to publish the branch. How should I proceed.
