### ISSUE TITLE
Change Liked to Community

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#209]
We are shifting gears from the concept of likes towards community. This means that the sidebar needs to be updated to say "community" instead of "liked". This includes changing the icon on the sidebar to something like the image below as well as changing the link and routing to navigate to a "community" page.
<img width="437" alt="image" src="https://github.com/UTDNebula/jupiter/assets/76502130/d054847c-de4b-42d2-afb3-00b0d466e51f">

**Comment by nl32** [comment]
Resolved
