### ISSUE TITLE
Package.json: '@types/react' and 'react' major version not matching

### ISSUE THREAD

**Issue by gilnicki** [UTDNebula/jupiter#24]
### What did you expect to happen?

After installing project dependencies with `yarn`, `yarn dev` should start the development server.

### What happened?

Command `yarn dev` returns the following error:
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file 
from your package root (and any TypeScript files in your pages directory).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Cause
The **_react_** version in the current package.json is `17.0.2` and **_@types/react_** is `^18.0.1` (which actually resolves to `18.0.21`) 

### Possible solutions
- Downgrading the **_@types/react_** version to `17.0.2` fixes the error.
-  Running `npm install` fixes the the error too. This is because `package-lock.json` has locked the version of **_@types/react_** to `18.0.1` and for some reason yarn is fine with that. However the types should be at least the same major version as the main package. 

### Version

Pre-release (Development)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
Thanks for the detailed bug report!

Sounds like for now setting the version to `17.0.2` in both places might be a good quick fix before we properly evaluate an update for React.

**Comment by RubenOlano** [comment]
Updating to next with next@latest seems to have fixed the issue for me.
I used `yarn add next@latest` to fix the issue.

**Comment by Jake3231** [comment]
@RubenOlano Is it correct that this is resolved in the latest changes?

**Comment by RubenOlano** [comment]
Yup, fixed it with the organization grid pr

**Comment by Jake3231** [comment]
Closing, as it seems this issue is resolved. @gilnicki please reopen if this issue occurs again.
