### ISSUE TITLE
Correct spacing behavior between listed organizations in the Directory

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#3]
Currently, organizations listed in the directory have odd spacing under some conditions. When there is ample horizontal space, the organizations appear squished together, even if they have plenty of space to be more spread out. Organizations may also unexpectedly move to a new line when there is enough horizontal space to stay on the previous line.
![Screen Shot 2022-04-11 at 1 04 11 PM](https://user-images.githubusercontent.com/13911970/162801695-c043d846-98bc-4564-bc15-1a4d32605829.png)

**Comment by Jake3231** [comment]
Possibly fixed in eec6f04dd90c053cab03ddbf833f7790e0fec325. This should be tested on a variety of form factors (mobile, desktop, etc).

**Comment by Jake3231** [comment]
This still does not work correctly on very large or very small (mobile) screen widths. On mobile widths the orgs appear squished together, and on very large widths orgs do not move to use less lines as width increases.

**Comment by Buchimi** [comment]
This commit could also not be found in this repository
![unknown](https://user-images.githubusercontent.com/61808599/165410311-dafb04f4-bdae-4d0c-819d-16a7aaf8a59a.png)

**Comment by Buchimi** [comment]
under the pages directory, in the directory.tsx file, editing the numbers here
`<Col
              key={org.name}
              xs={{ span: 4 }}
              sm={{ span: 3 }}
              md={{ span: 3 }}
              lg={{ span: 3 }}
              xl={{ span: 5 }}
            >` 
has an effect on the visual output

**Comment by Jake3231** [comment]
Continuing work on https://github.com/UTDNebula/jupiter/tree/3-ord-card-spacing.

**Comment by Buchimi** [comment]
The spacing looks good now!

**Comment by Jake3231** [comment]
Likely not needed with changes in #36.

**Comment by Jake3231** [comment]
Closing for now. Can be reopened if this was not fixed.
