### ISSUE TITLE
Types Missing for react-flex-grid

### ISSUE THREAD

**Issue by RubenOlano** [UTDNebula/jupiter#31]
### What did you expect to happen?

When importing components from react-simple-flex-grid, I expect to be able to use the components with no errors 

### What happened?

When importing, I get the following error:
`Could not find a declaration file for module 'react-simple-flex-grid'. `

While this error does show up, it does not prohibit me from running the development server

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Could not find a declaration file for module 'react-simple-flex-grid'. '/Users/ruben/jupiter/node_modules/react-simple-flex-grid/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-simple-flex-grid` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-simple-flex-grid';`
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
May be resolved with the changes in #36.

**Comment by Jake3231** [comment]
Should now be resolved.

**Comment by RubenOlano** [comment]
No errors  👍
