### ISSUE TITLE
With the updated directory implementation, images don't load

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#37]
### What did you expect to happen?

I expect that organizations in the directory will have some sort of image.

### What happened?

When viewing the new directory implementation, orgs have no image. This seems to be because image URLs need to be updated.

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
error - TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6406:34)
    at node:internal/deps/undici/undici:6727:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: getaddrinfo ENOTFOUND utdallas-cdn.presence.io
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'utdallas-cdn.presence.io'
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
Updated some URLs. I'm currently having issues getting local images to load correctly from the sample data. So far I've tried placing something like `"../assets/media/images/utd-monogram-solid-rgb.jpg"` as the image link, though Next is unable to find the image. 

@RubenOlano Do you potentially know what could could be going on? I saw some info saying that assets need to be in the `public` folder, though it seems that this isn't true on newer versions of Next.

**Comment by RubenOlano** [comment]
I believe that for the nextjs image element, it's easiest to put them in the public folder. Then all it is just doing `'/{image_name}'` to get that image.

**Comment by Jake3231** [comment]
I'll try that, especially since these are placeholders.

**Comment by Jake3231** [comment]
That worked much more easily!
