### ISSUE TITLE
Sample Tags data structure needed

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#45]
# Overview

As a user, I should be able to utilize search filtering by a predefined list of tags. In order to fully test the developing UI, we will need to include a sample data structure containing valid tags usable in Jupiter.

# Proposal

- [ ] Establish sample file of valid tags
- [ ] Ensure that sample organizations are using these tags
- [ ] Allow filtering UI to enumerate valid tags (no further functionality needed for this)

**Comment by RubenOlano** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/76502130/196464841-a9bdc578-f176-4fa4-b25b-44bb03568e08.png">
Something along these lines

**Comment by Jake3231** [comment]
That seems pretty reasonable. Would we need to then enumerate over the possible values of type `Tags` in order to fill out filtering UI, and similar?

**Comment by RubenOlano** [comment]
For the filtering, I think typescript can automatically do most of that for us. My only concern is having to constantly update the tags if new tags pop up

**Comment by Jake3231** [comment]
In order to simulate the backend, could we have a JSON file or similar that will still require manual updating, but will be less hard-coded?

**Comment by RubenOlano** [comment]
I'm gonna have to do more research on that but I'll look into it

**Comment by RubenOlano** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/76502130/196758984-dea06013-b9bb-4266-bcc1-c0b94e83b351.png">
I think this is the closest I could get. We need to basically make an immutable type within a file which is not available if we import from another file

**Comment by Buchimi** [comment]
Ever tried a list of enums? 
Loop through the list and display the appropriate tags

**Comment by Jake3231** [comment]
Currently on hold as we're not shipping with tags.
