### ISSUE TITLE
Updated homepage tagline needed

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#47]
# Overview

Currently, the Jupiter homepage displays a marketing tagline below the product name. This needs to be simplified and adjusted to look more professional.

# Proposal

- [ ] Change tagline to say "Get Connected on Campus"
- [ ] Increase tagline font size slightly so that it is more readable 

## Supplementary Information

Current design:

![Screenshot 2022-10-19 at 11 04 56 AM](https://user-images.githubusercontent.com/13911970/196744916-6157fe57-5cda-4cec-a9b6-860b32e2a783.png)

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.
