### ISSUE TITLE
Create user profile image in place of "Sign Up" button when signed in

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#51]
# Overview

As a user, I should be able to view my signed-in profile at the top right corner of the app, and access profile settings.

# Proposal

This requires tracking a logged-in state, and switching the "Sign Up" (or Sign In) button in the navbar to be a profile picture which can link to an account settings page.

For now, there may need to be a temporary way to toggle this for testing, as we want to be able to still access both the onboarding and the user account settings pages. This might even include changing some state in the code for testing purposes.

**Comment by RubenOlano** [comment]
Is it alright if I just make a mock sign-in state? Something like when I click the sign in button I show the profile pic and when I click the logout then I switch back.

**Comment by Jake3231** [comment]
Yeah, that sounds like a pretty good solution! We will need to connect that with the onboarding UI as well once that is ready.
