### ISSUE TITLE
No tab title for About page

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#58]
### What did you expect to happen?

I expect that the title of the tab for the About page to be "About - Jupiter"

### What happened?

Currently, the tab shows `localhost:3000`.
![Screenshot 2022-10-24 at 10 48 06 AM](https://user-images.githubusercontent.com/13911970/197569309-0854c083-267d-4e48-a8ad-82e1b60bec82.png)

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ujwalkumar1995** [comment]
Hey @Jake3231 
I can try to fix this. Could you please assign?
