### ISSUE TITLE
Directory: Entire pages scrolls rather than just org grid

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#66]
### What did you expect to happen?

I expect that when scrolling with the cursor inside the organization grid that only the grid's contents will scroll.

### What happened?

When scrolling with the cursor inside the organization grid in the Directory, the entire page scrolls. Additionally, when adding additional sample organizations, the page height increases.

### Version

Pre-release (Development)

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RubenOlano** [comment]
This is addressed in #43

**Comment by Jake3231** [comment]
You're right, just saw that was fixed after merging #50 .
