### ISSUE TITLE
Update favicon for Jupiter

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#7]
We need to add a correct global favicon for Jupiter.

**Comment by Jake3231** [comment]
Favicon added in f7f001433c4336b6be1aca2816ba2e3e686f6493

**Comment by Buchimi** [comment]
The favicon isn't in the development repo, it looks like it's a commit to a fork of this repository

**Comment by Buchimi** [comment]
made a fix to that in the latest push

**Comment by Jake3231** [comment]
> made a fix to that in the latest push
Just to clarify, was the favicon in tabs not working even after the mentioned commit?

**Comment by Buchimi** [comment]
It wasn't, also if you take a look at the commit it says it doesn't belong to this repository

**Comment by Jake3231** [comment]
> It wasn't, also if you take a look at the commit it says it doesn't belong to this repository.

@WillieCubed Could this be caused by the process of temporarily moving the repo between accounts, or might this be some other issue?

**Comment by Buchimi** [comment]
![unknown](https://user-images.githubusercontent.com/61808599/165410136-aa2be265-2931-46ee-a8ed-58e930e56d1e.png)
