### ISSUE TITLE
Org Officer Create Org UI needed

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#75]
# Overview

As an organization administrator, I should be able to create a new organization on Jupiter.

There should be some non-functional UI which shows some kind of form allowing org officers to create a new organization. Likely this would be submitting a request to us to be reviewed, though those details need to be ironed out.

# Proposal

This likely would be developed with/after #52. 

- [ ] Create placeholder/temporary state to track whether logged in user is an org officer (optional)
- [ ] If user is an officer of an org, show special UI to begin creating an org
- [ ] Create a new page (or some UI) that shows a form of basic data needed
- [ ] Simulate submitting the form to the backend, and return to previous page

I'm not sure where exactly this should live - it seem logical for this to be in the app settings. Maybe an org officer would have an "Organization administration" tab, and would show a "create new organization" button if they aren't assigned to one currently.

**Comment by Master7130** [comment]
To handle state are we going to be using React Context API or Redux?

**Comment by Master7130** [comment]
I'm not sure but [this article](https://www.scalablepath.com/react/context-api-vs-redux) would be helpful in choosing between the two.

**Comment by RubenOlano** [comment]
I think we can use instead of a context API would be using a library like [React Query](https://tanstack.com). It basically replaces the need to use context libraries due to how it caches the information. Just throwing around another idea

**Comment by Jake3231** [comment]
I do see that Planner is user Redux.

For React Query's benefit, does that allow more advanced client-side caching than the others?

**Comment by RubenOlano** [comment]
Yeah, it allows us to granularly refetch data if needed or make it so the data does not become stale. One thing that we may need to consider is how Next13 affects the context libraries because of the new way it'll handle routing with the app directory

**Comment by Jake3231** [comment]
Sounds like Query will be the way to go, save for Next 13.

**Comment by RubenOlano** [comment]
Currently we don't have a design for this, but we can do a rough implementation until we do

**Comment by Jake3231** [comment]
@nl32 Linking this issue, as the PR addresses it also.
