### ISSUE TITLE
IDEA: Study groups

### ISSUE THREAD

**Issue by Buchimi** [UTDNebula/jupiter#76]
# Overview

As a stretch goal or a future goal, I would like to see a study group feature in Jupiter. 

# Features
- One time groups that expire post some due date
- Groups revolve around the studying of specific topics for specific classes
- Groups may be tied to a class section

**Comment by Jake3231** [comment]
This is a really cool idea! Also attaching the notes from today about this:
```

- Ex: want to study tomorrow at 6-8PM, Jupiter shares study session with classmates
- People could search for CS3377 study groups, search for Threads (Example)
- Anyone can join, but it gets deleted after the scheduled time
- Might fit well in scope of Jupiter, or other Nebula project
- Study Session could maybe could be an Event in Jupiter
- Could include location, time, organizer

```

**Comment by RubenOlano** [comment]
We need to finalize the core design for Jupiter before tackling this
