### ISSUE TITLE
Investigate Upgrading to Next.js 13

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#77]
# Overview

This issue is tracking work to investigate potentially upgrading Jupiter to use Next.js 13. This major version update could allow significant benefits, though we need to investigate if it has basic compatibility with the existing architecture, and a potential upgrade path to take advantage of new features. New features of particular interest are server-side components and Turbopack.

For potential architectural/data changes, consideration should be given to the long-term plan for the API team to manage Jupiter's backend, so coordination would be needed to ensure they can support what our frontend is relying on.

# Proposal

- [ ] Investigate new features and potential application to Jupiter
- [ ] Ensure basic compatibility with the existing implementation
- [ ] Incrementally update file structure
- [ ] Incrementally update data/backend structure

## Supplementary Information

Blog post with more info: https://nextjs.org/blog/next-13

**Comment by Jake3231** [comment]
@RubenOlano is this resolved by #121 ?

**Comment by RubenOlano** [comment]
> @RubenOlano is this resolved by #121 ?

Yup
