### ISSUE TITLE
Proposed Student Model

### ISSUE THREAD

**Issue by Buchimi** [UTDNebula/jupiter#78]
# Proposal
My proposal for how a student is perceived by the website. Feel free to add, remove, debate, etc.
## Student
- First name
- Last name
- Email address
- Year
  - Freshman
  - Sophomore
  - Junior
  - Senior
  - Grad student
- transfer
  - True
  - False
- major 
- minor

**Comment by Jake3231** [comment]
Does this proposal allow for representing grad students?

Also, what is the relation to the user's metadata (interests, member clubs, etc) with this model?

**Comment by Buchimi** [comment]
You could have an extra option for grad student after senior (I think they are all just called grad students) 
Also, with clubs, you could possibly have each club have their own tables for who is a member of said club
We could also have a general table for which student belongs to what club

**Comment by Jake3231** [comment]
My only concern with having the clubs inherently own the list of members would be that it would become expensive to find out which clubs a user is in. Could it work where a user object has a list of clubs id's it's a member of, and clubs also have a list of member user ids, which are updated in sync? Not sure if we would run into out-of-sync issues.

**Comment by Buchimi** [comment]
I think that'll be possible, relational databases allow for these type of many to many relationships

**Comment by RubenOlano** [comment]
I think this should be fixed now right?

**Comment by RubenOlano** [comment]
Current design implement this 👍🏽
