### ISSUE TITLE
Misaligned buttons in nav bar

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#8]
In the app's top navigation bar, the About and Sign Up buttons are misaligned. The About button appears too high. This happens only when adding a top/bottom padding to the adjacent Sign Up button.

<img width="1438" alt="Screen Shot 2022-04-20 at 7 55 19 PM" src="https://user-images.githubusercontent.com/13911970/164350361-c458bacc-7ed9-46b3-a515-0c95241f9236.png">

**Comment by Buchimi** [comment]
Fixed that in the latest push
