### ISSUE TITLE
New FilterItem component needed

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#81]
# Overview

As a user I should be able to filter organizations and events using predefined filter properties.

A good first step toward achieving this is to create a new element that can be used inside the directory filter dropdown.

# Proposal
Attached is an image of this design in the Figma document. This should appear as a checkbox with a label, which can be toggled on and off. For this proposal, only the single element is needed, and it can be later wired up to the filtering data.

## Supplementary Information
Snapshot from design doc:

<img width="304" alt="Screenshot 2022-10-29 at 12 53 00 PM" src="https://user-images.githubusercontent.com/13911970/198846056-94c96dc3-ca87-44b4-8bb8-6b87fdb09bac.png">

**Comment by Jake3231** [comment]
This may have since been resolved

**Comment by RubenOlano** [comment]
Should be fixed by #123
