### ISSUE TITLE
Create Events placeholder on homepage

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#9]
Currently, the Homepage includes just the banner images with the title "Jupiter" and a tagline. There needs to be a list of recommended events below that, as included in the design spec:
![Screen Shot 2022-04-20 at 10 42 23 PM](https://user-images.githubusercontent.com/13911970/164367586-3e52bded-fe67-4668-8339-fc3ec3e2cb07.png)

**Comment by Master7130** [comment]
Would the placeholders be a new component or should I use the OrganizationCard component?

**Comment by Jake3231** [comment]
This should be some new component specifically for events. We'll likely want to have one tailored to the homepage showing less information than in the events browser, but enough to still convey the event. The Figma design is ambiguous as to what this should look like exactly. One idea could be an event image overlayed with the event title and club name.

**Comment by Master7130** [comment]
On second thought that was really not a good question when the issue is titled "Create _Events_ Placeholder." Thanks for clarifying.
