### ISSUE TITLE
Additional fields needed for org data

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/jupiter#95]
# Overview

As a user, I should be able to view the following information about an org:

- [x] Org logo - standard sizes
- [x] description 
- [x] Contact info
- [x] Website
- [ ] Categories
- [x] Tags
- [x] Name

# Proposal

- [ ] Add new fields in data
- [ ] Add sample data to orgs

## Supplementary Information

To give your feature more chance at being implemented, feel free to attach any
other documentation. For something highly-user facing, a UI mock-up or some
other form of wireframe is required.

**Comment by RubenOlano** [comment]
Currently resolved with placeholder data
